"""create contacts table

Revision ID: 761be5294581
Revises: f91c3e820ab7
Create Date: 2026-05-12 03:16:10.214425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761be5294581'
down_revision: Union[str, None] = 'f91c3e820ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_properties_created_at', table_name='properties')
    op.drop_index('ix_properties_location', table_name='properties')
    op.drop_index('ix_properties_price', table_name='properties')
    op.drop_index('ix_properties_property_type', table_name='properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_properties_property_type', 'properties', ['property_type'], unique=False)
    op.create_index('ix_properties_price', 'properties', ['price'], unique=False)
    op.create_index('ix_properties_location', 'properties', ['location'], unique=False)
    op.create_index('ix_properties_created_at', 'properties', ['created_at'], unique=False)
    # ### end Alembic commands ###
